version: "3.8"

services:
  php:
    build: .
    # user: "501:20"
    restart: always
    ports:
      - 8081:80
    volumes:
      - ./build/:/var/www/html
    #   - ./vendor:/var/www/html/vendor
    # env_file:
    #   - ./.env
    # depends_on:
    #   - db
  
#   pma:
#     image: phpmyadmin/phpmyadmin
#     links:
#       - db
#     environment:
#       PMA_HOST: db
#       PMA_PORT: 3306
#       PMA_ARBITRARY: 1
#     restart: always
#     ports:
#       - 8082:80

#   db:
#     image: mysql:8.0.32
#     restart: always
#     volumes:
#       - ./mysql-data:/var/lib/mysql
#     env_file:
#       - ./.env